services:
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - DB_URI=mongodb://database:27017/finalproject
    depends_on:
      - database

  frontend:
    build:
      context: ./frontend
    ports:
      - "4200:80"

  database:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "8080:8080"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data:
